src/Entity/Chambre.php
<?php

namespace App\Entity;

use App\Repository\ChambreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChambreRepository::class)]
class Chambre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $description_courte = null;

    #[ORM\Column(length: 255)]
    private ?string $description_longue = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column]
    private ?int $prix_journalier = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'chambre', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;

    // #[ORM\Column]
    // private ?int $prix_total = null;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescriptionCourte(): ?string
    {
        return $this->description_courte;
    }

    public function setDescriptionCourte(string $description_courte): self
    {
        $this->description_courte = $description_courte;

        return $this;
    }

    public function getDescriptionLongue(): ?string
    {
        return $this->description_longue;
    }

    public function setDescriptionLongue(string $description_longue): self
    {
        $this->description_longue = $description_longue;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): self
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setChambre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getChambre() === $this) {
                $commande->setChambre(null);
            }
        }

        return $this;
    }

    // public function getPrixTotal(): ?int
    // {
    //     return $this->prix_total;
    // }

    // public function setPrixTotal(int $prix_total): self
    // {
    //     $this->prix_total = $prix_total;

    //     return $this;
    // }
 }

src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Chambre $chambre = null;


    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_arrivee = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_depart = null;

    #[ORM\Column]
    private ?int $prix_total = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getChambre(): ?Chambre
    {
        return $this->chambre;
    }

    public function setChambre(?Chambre $chambre): self
    {
        $this->chambre = $chambre;

        return $this;
    }

    public function getDateArrivee(): ?\DateTimeInterface
    {
        return $this->date_arrivee;
    }

    public function setDateArrivee(\DateTimeInterface $date_arrivee): self
    {
        $this->date_arrivee = $date_arrivee;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getPrixTotal(): ?int
    {
        return $this->prix_total;
    }

    public function setPrixTotal(int $prix_total): self
    {
        $this->prix_total = $prix_total;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $pseudo = null;


    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 20)]
    private ?string $nom = null;

    #[ORM\Column(length: 20)]
    private ?string $prenom = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $civilite = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Commande::class)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setUser($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getUser() === $this) {
                $commande->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/Projet5Controller.php
<?php

namespace App\Controller;

use App\Entity\Chambre;
use App\Entity\Commande;
use App\Form\CommandeType;
use App\Repository\ChambreRepository;
use App\Repository\CommandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class Projet5Controller extends AbstractController
{
     
    #[Route('/projet5/home', name: 'home')]
    #[Route('/', name: 'home1')]
    public function home(ChambreRepository $repo)
    {
        $chambres = $repo->findAll();
        return $this->render("projet5/home.html.twig", [
            'Chambres' => $chambres
        ]);
    }

    #[Route('/projet5/show', name: 'show')]
    public function show(ChambreRepository $repo)
    {
        $chambres = $repo->findAll();
        return $this->render("projet5/show.html.twig", [
            'Chambres' => $chambres
        ]);
    }
    

    #[Route('/projet5', name: 'app_projet5')]
    public function index(ChambreRepository $repo): Response
    {
        return $this->render('projet5/index.html.twig', [
            'chmbr' => $repo->findAll()
        ]);
    }
    #[Route('/projet5/reservation/{id}', name: 'reservation_chambre')]
    public function reservation(Chambre $chambre = null, EntityManagerInterface $manager, Request $rq)
    {
        if (!$chambre)
            return $this->redirectToRoute('app_projet5');

        $commande = new Commande;
        $form = $this->createForm(CommandeType::class, $commande);
        $form->handleRequest($rq);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $commande->setUser($user);
            $commande->setDateEnregistrement(new \DateTime());
            $commande->setChambre($chambre);
            $commande->setPrenom($user->getPrenom());
            $commande->setNom($user->getNom());
            $commande->setEmail($user->getEmail());
            


            $depart = $commande->getDateDepart();
            if ($depart->diff($commande->getDateArrivee())->invert == 1) {
                $this->addFlash('danger', 'Une période de temps ne peut pas être négative.');
                return $this->redirectToRoute('reservation_chambre', [
                    'id' => $chambre->getId()
                ]);
            }
            $jours = $depart->diff($commande->getDateArrivee())->days;
            $prixTotal = ($commande->getChambre()->getPrixJournalier() * $jours) + $commande->getChambre()->getPrixJournalier();
            $commande->setPrixTotal($prixTotal);
            $commande->setPrixTotal($prixTotal);

            $manager->persist($commande);
            $manager->flush();
            $this->addFlash('success', 'Votre reservation a bien été enregistrée !');
            return $this->redirectToRoute('profil');
        }

        return $this->renderForm('projet5/reservation.html.twig', [
            'form' => $form,
            'cham' => $chambre
        ]);
    }

    #[Route('/projet5/profil', name: 'profil')]
    public function profil(CommandeRepository $repo)
    {
        $commandes = $repo->findBy(['user' => $this->getUser()]);

        return $this->render("projet5/profil.html.twig", [
            'commandes' => $commandes
        ]);
    }










}

templates/projet5/home.html.twig
{% extends "base.html.twig" %}


{% block title %}Accueil{% endblock %}


{% block body %}
    <style>
        .accueil {
            background-image: url('https://th.bing.com/th/id/R.f943f4168afe7f0ae009c2e8e8abed73?rik=psA8LKTVD3%2bYaw&riu=http%3a%2f%2fhotelkitchen.org%2fwp-content%2fuploads%2f2016%2f06%2fThinkstockPhotos-824284124_75.jpg&ehk=lg7DW1TmfnskT5gaNp8dWebBIUZOqCfPc0ZJ3rxKWpA%3d&risl=&pid=ImgRaw&');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 90% 100%;
            height: 500px;
            text-align: center;
        }

        .contenaire {
            display: flex;
            flex-direction: row;
            flex-wrap: nowrap;
            justify-content: space-between;
            margin-top: 450px;

        }
        .carousel {
            background-repeat: no-repeat;
            background-size: 100% 100%;
            text-align: center;
        }

        .img-fluid {
            width: 150px;
            height: 150px;
            border-radius: 100px;

        }
    </style>
<div class="accueil ">

        <h2>BIENVENUE</h2>
        <h6 class="mb-5 red">Découvrez norte restaurant</h6>
        <div class="contenaire">
            <div class="cercle text-center">
                <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 4"></button>
                    </div>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="https://th.bing.com/th/id/R.1eed0064af4bcbaa976d4b50b5e8874b?rik=%2fDol7KljEjV5QA&riu=http%3a%2f%2fwww.bemextours.com%2fwp-content%2fuploads%2f2016%2f06%2fcroatie-split-hotel-meridien-lav-restaurant.jpg&ehk=2pyg9Dc6jTdVhvu%2fKshFVUo9iu32PBGPQ7O7uJpat7Y%3d&risl=&pid=ImgRaw&r=0" class="img-fluid" alt="...">
                        </div>
                        <div class="carousel-item ">
                            <img src="https://th.bing.com/th/id/R.a3ff4908bc317490871f0049a274e883?rik=YL9104G5wk0Few&riu=http%3a%2f%2fwww.weightloss.com.au%2fimages%2fhealthy-recipes%2fdinner%2fseed-must-lamb-lge.jpg&ehk=Z58Dsl17GuFQ1cB5IwJRxSHkYhIp0qpIDYcOTrMtziM%3d&risl=&pid=ImgRaw&r=0" class="img-fluid" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="https://assets.afcdn.com/manage/bloc/D20161202/carre-blanquette-120608_L.jpg" class="img-fluid" alt="...">
                             </div>
                        <div class="carousel-item">
                            <img src="https://assets.afcdn.com/manage/bloc/D20161202/carre-blanquette-120608_L.jpg" class="img-fluid" alt="...">
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
                <div class="card-body ">
                    <h5 class="card-text ">Carte</h5>
                    <p class="card-text">Venez découvrir nos Menus</p>
                    <a href="/pdf/carte.pdf" class="btn btn btn-primary mb-2">Voire la carte</a>
                </div>
            </div>
        </div>

    </div>

</div>



{% endblock %}

templates/projet5/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Projet5Controller!{% endblock %}

{% block body %}
<div class="accueil ">
<h2>BIENVENUE</h2>
<h6 class="mb-5 red">Découvrez nos Chambre</h6>

<style>
		.accueil{
background-image: url('https://th.bing.com/th/id/OIP.NRydoEFLY9kigHB78iRIsgHaEK?pid=ImgDet&rs=1');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 80%;
  height: 500px;
  text-align: center;

		}
		.card{
			text-align: center;
		}
</style>

			<button class="btn btn-primary" style="margin-top: 250px">HouseHotel | Découvrez nos chambres</button>

		</div>

	<div class="row">
		{% for item in chmbr %}
			<div class="col-md-4">
				<div class="card mb-3" style="width: 18rem;"> 
					<h3 class="card-header">{{ item.titre }}</h3>
					<img src="{{ item.photo }}" class="img-fluid rounded-start" alt="...">
					<div class="card-body">
						<p class="card-text">{{ item.descriptionCourte }}</p>
						<p class="card-text text-end fw-bold">{{ item.prixJournalier }}€/j</p>
					</div>
					<div class="card-body text-end">
                    {# <a href="#" class="card-link btn btn-primary">Réserver</a> #}
						<a href="{{ path('reservation_chambre', {id: item.id}) }}" class="card-link btn btn-primary">Réserver</a>
                        
					</div>
				</div>
			</div>
		{% endfor %}
	</div>





{% endblock %}

templates/projet5/profil.html.twig
{% extends "base.html.twig" %}

{% block body %}

{% for label, msgs in app.flashes %}
		{% for msg in msgs %}
			<div class="alert alert-{{ label }} text-center">
				{{ msg }}
			</div>

		{% endfor %}
	{% endfor %}

<h1 class="text-center">Liste des commandes</h1><br><br>

<table class="table">
<thead>
    <tr>
        
        <th>Chambre</th>
        <th>date d'arrivée</th>
        <th>date de départ</th>
        <th>prix total</th>
        <th>prenom</th>
        <th>nom</th>
        <th>telephone</th>
        <th>email</th>
        <th>date d'enregistrement</th>
        {# <th>action</th> #}



    </tr>
</thead>
<tbody>
{% for item in commandes %}
    <tr>
        
        <td>{{ item.dateEnregistrement|date('d/m/Y à H:i:s') }}</</td>
        <td>{{ item.chambre.titre }}</td>

        
        <td>{{ item.chambre.titre }}</td>
        <td>{{ item.dateArrivee|date('d/m/Y à H:i:s') }}</</td>
        <td>{{ item.dateDepart|date('d/m/Y à H:i:s') }}</td>
        {# <td>{{ item.prixTotal }}€</td> #}
        <td>{{ item.user.prenom }}</td>
        <td>{{ item.user.nom }}</td>
        {# <td>{{ item.user.telephone }}</</td> #}
        <td>{{ item.user.email }}</td>
        <td>{{ item.dateEnregistrement|date('d/m/Y à H:i:s') }}</</td>   
        



    </tr>
{% endfor %}
</tbody>
</table>

{% endblock %}

templates/projet5/reservation.html.twig
{% extends "base.html.twig" %}

{% block body %}

{% for label, msgs in app.flashes %}
		{% for msg in msgs %}
			<div class="alert alert-{{ label }} text-center">
				{{ msg }}
			</div>

		{% endfor %}
	{% endfor %}

<h1 class="text-center">Réserver chambre </h1>

<div class="col-md-6">
				<div class="card mb-3" style="width: 18rem;">
					<h3 class="card-header">{{ cham.titre }}</h3>
					<img src="{{ cham.photo }}" alt="Image du chambre">
					<div class="card-body">
						<p class="card-text">{{ cham.descriptionCourte }}</p>
						<p class="card-text text-end fw-bold">{{ cham.prixJournalier }}€</p>
					</div>
				</div>
			</div>

{{ form_start(form) }}

{{ form_row(form.dateDepart) }}
{{ form_row(form.dateArrivee) }}

<button type="submit" class="btn btn-primary">Réserver à ces dates</button>

{{ form_end(form) }}

{% endblock %}

templates/projet5/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello{% endblock %}

{% block body %}


		
<div class="accueil ">
{# <h2>BIENVENUE</h2> #}
<h1 class="mb-5 red">NOS CHAMBRE</h1>
					
</div>





    

<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="https://th.bing.com/th/id/OIP.n82o0oioofp1Rqr5JqNB_AHaDt?pid=ImgDet&rs=1" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Chambre Confort</h5>
        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac lorem hendrerit, tempus turpis vitae, aliquam massa. Fusce euismod ipsum ut dui gravida,</p>
        
      </div>
      </div>
      </div>

      <br><br>

      <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="https://www.fourseasons.com/alt/img-opt/~70.1530/publish/content/dam/fourseasons/images/web/GEN/GEN_268_original.jpg" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Chambre suite</h5>
        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac lorem hendrerit, tempus turpis vitae, aliquam massa. Fusce euismod ipsum ut dui gravida,</p>
        
      </div>
      </div>
      </div>
      </div>
      <br><br>
      

      <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="https://th.bing.com/th/id/OIP.3lUjvtshN6uD0k_wfxdaLwHaE8?pid=ImgDet&rs=1" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Chambre classique</h5>
        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac lorem hendrerit, tempus turpis vitae, aliquam massa. Fusce euismod ipsum ut dui gravida,</p>
        
      </div>
      
      
    </div>
  </div>
</div>









{% endblock %}